workspace: true

stages:
  - build
  - deploy

jobs:
- name: build
  stage: build
  image: sunasteriskrnd/php-workspace:7.4
  services:
  - image: mysql:5.7
    name: mysql_test
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_username
      MYSQL_PASSWORD: test_password
  environment:
    APP_ENV: testing
  cache:
  - key: comopser_vendor_$CI_BRANCH
    paths:
      - vendor
  before_script:
  - cp .env.testing.example .env.testing
  - composer install
  - php artisan key:generate
  - php artisan migrate
  script:
  - composer sniff
  - composer test
  after_script:
  - echo "Finish job"
  only:
    branches:
    - master
    - develop
    events:
    - pull_request

- name: deploy:staging
  stage: deploy
  image: sunasteriskrnd/php-workspace:7.4
  before_script:
  - composer require deployer/deployer --dev
  script:
  - php vendor/bin/dep deploy staging -vv
  only:
    branches:
    - develop
  except:
    events:
    - pull_request
